### ISSUE TITLE
星の挙動を作成する

### ISSUE THREAD

**Issue by AnanMatumoto** [AnanMatumoto/StarStory#6]
### 関数を用いて挙動を作成する

**挙動**
- 加速
一定の間、ｘの移動量を２倍にする。
- [x] 出来たらチェック

- ジャンプ
ｙの移動量を1.3ｆ（128ｐｘのオブジェクトを超えれるくらい）増やす。
一定の高さに来たら、徐々に減速する。
- [x] 出来たらチェック

- 停止
移動量ｘを一定時間０にする。
- [x] 出来たらチェック

------------------------------------------
- [x] コードレビューもしてもらった

終わったらエフェクトつける
（キーフレームアニメーション作る？）

**Comment by AnanMatumoto** [comment]
@yttmwork 
お疲れ様です。
プレイヤーの挙動がジャンプ、加速が
複数のオブジェクトに対して実装できましたので、
一度、コードをレビューをお願いしたいです。
お手数ではございますが、よろしくお願いいたします。

**Comment by yttmwork** [comment]
お疲れ様です。
コミットログを追っていく形でレビューしました。
GW中に各クラスの流れなどを追っていきながらのレビューを
時間が作れたらやりたいと思います。

**Comment by AnanMatumoto** [comment]
一度実装が終わっているので本件クローズ

**Comment by AnanMatumoto** [comment]
一旦、実装が終わったので本件クローズ
